### ISSUE TITLE
code

### ISSUE THREAD

**Issue by cbanwell** [EmmetOT/HDRPGrass#1]
Hiya, would love to have a copy of the code, maybe we can collaborate, this is exactly the approach I'd like to try, I'd be especially interested to see how you implemented the distribution over the tris of the mesh.  We currently work with irregular meshes and find that it's a real problem getting a good distribution of grass over the mesh.

PS. also locked down (well hopefully not anymore) in carrickmacross

**Comment by EmmetOT** [comment]
I just went to say "I'm already sharing the code, it's right there!" and I
looked at the repository and it's been sitting there un-pushed for over a
month. I'm so glad you messaged me now hahaha!

Anyway, it's pushed now, and all the code relevant to your question is here.

<https://github.com/EmmetOT/HDRPGrass/blob/main/HDRPGrass/Assets/Grass/Compute/Shaders/Grass_Compute_ComputeShader.compute>
There's actually nothing fancy about the way I do it.

I calculate the total surface area of the mesh by adding up the area of
every polygon. At the same time I create a buffer and store the area of
each polygon separately.

Next, I create an 'accumulated area' buffer which is just the area buffer
but every value is the sum of all the previous areas. You can store this
buffer so you don't have to recalculate it every time.

I pick a random number between 0 and the mesh's total surface area, and
step through this accumulated area buffer until I hit a value which is
greater than my random number. I now have the index of the mesh polygon I
want to place my grass blade on, and the chance of me picking any
particular polygon is directly proportional to its area.

Finally, I pick a random point on that triangle
<https://math.stackexchange.com/questions/18686/uniform-random-point-in-triangle-in-3d>,
and that's it.

Hope this helps!

Emmet
<https://github.com/EmmetOT/HDRPGrass/blob/main/HDRPGrass/Assets/Grass/Compute/Shaders/Grass_Compute_ComputeShader.compute>

**Comment by cbanwell** [comment]
Thanks Emmet that's awesome, and thanks again for the explanation, I'll have a play with it tomorrow
